services:
  database:
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    env_file:
      - postgres_env.env
    volumes:
      - ./db-data:/etc/data
    
volumes:
  db-data: 
    driver: local